version: "3.9"
services:
  httpbin:
    image: mccutchen/go-httpbin:v2.5.0
    ports:
      - 8080:8080
  coraza:
    build:
      context: .
      target: coreruleset
    volumes:
      - ./docker/e2e/e2e-rules.conf:/etc/coraza-spoa/rules/000-e2e-rules.conf
      - cor:/var/log/coraza-spoa
    ports:
      - 9000:9000
    command:
      [
        "sh",
        "-c",
        "/usr/bin/coraza-spoa --config /etc/coraza-spoa/config.yaml 2>&1 | tee /var/log/coraza-spoa/coraza.log"
      ]
  haproxy:
    depends_on:
      - coraza
      - httpbin
    image: ${HAPROXY_IMAGE:-haproxy:2.7-alpine}
    command:
      [
        "sh",
        "-c",
        "haproxy -d -f /usr/local/etc/haproxy/haproxy.cfg 2>&1 | tee /var/lib/haproxy/hap.log"
      ]
    ports: [ "4000:4000" ]
    volumes:
      - type: bind
        source: ./docker/haproxy
        target: /usr/local/etc/haproxy
      - hap:/var/lib/haproxy
  tests:
    depends_on:
      - haproxy
      - coraza
    build:
      context: docker/e2e
      dockerfile: ./Dockerfile.curl
    volumes:
      - hap:/haproxy
      - cor:/coraza
volumes:
  hap:
  cor:
